### ISSUE TITLE
Dotnet Standard 2.1 does not work anymore

### ISSUE THREAD

**Issue by ltmx** [GlitchEnzo/NuGetForUnity#595]
## Description

this error appears which did not occur in previous version, along with 4 other errors in the same file : 
`O:\Unity\Unity Packages\NuGetForUnity\src\NuGetForUnity\Editor\Configuration\ConfigurationEncryptionHelper.cs(63,42): error CS0103: The name 'ProtectedData' does not exist in the current context`

it seems it comes from this modification : 
[https://github.com/GlitchEnzo/NuGetForUnity/commit/5a1e29680437c762255e08402dcfe6d4ed10e084#diff-52613587d2158fef5548a1d606e611fbe4c0a741d29b7ac1e5bf8fe0f0cc9175](https://github.com/GlitchEnzo/NuGetForUnity/commit/5a1e29680437c762255e08402dcfe6d4ed10e084#diff-52613587d2158fef5548a1d606e611fbe4c0a741d29b7ac1e5bf8fe0f0cc9175)

my unity configuration is : 
![configuration](https://github.com/GlitchEnzo/NuGetForUnity/assets/47640688/89429f64-e12e-4bd8-ada8-cbada49e3176)

-   **NuGetForUnity Version:** 4.0.1
-   **Unity Version:** 2023.1.17f1
-   **Operating System:** Windows 11

**Comment by JoC0de** [comment]
OK Strange, for me it worked in 2023.1.11f1.
I will fix it...
