### PR TITLE
Disable autoReferenced in NuGetForUnity.asmdef

### PR DESCRIPTION
**Pull request by apkd**
This is a proposed workaround for IDE-side build problems caused by #672.

The `autoReferenced` setting causes the NuGetForUnity assembly to be added as a dependency to the Assembly-CSharp assembly, making it difficult to use certain IDE features (e.g., Rider's IL viewer, which requires the project to be built).

This change implies breaking backwards compatibility for users that rely on accessing the NuGetForUnity assembly from Assembly-CSharp and friends. I think it's a bit of an anti-pattern for an editor tool anyway, and extending NuGetForUnity can always be achieved via direct assembly references.

### CODE REVIEW

**Comment by TheXRMonk** [comment]
Wow, just in time! I was about to add my two cents on why "just deactivate the 'Project files generation for UPM packages'" is not viable for anyone who use writable packages as submodules or otherwise. <3

**Comment by apkd** [comment]
After some testing, it looks like the correct fix for #672 is to remove or empty the `csc.rsp` file.

The compilation errors are actually proceded by the warning:
```
4>Microsoft.Common.CurrentVersion.targets(2433,5): Warning MSB3243 : No way to resolve conflict between "System.IO.Compression, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System.IO.Compression, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b77a5c561934e089". Choosing "System.IO.Compression, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
```

Looks like `System.IO.Compression` is already brought in by default, and referencing it using `csc.rsp` causes a conflict. Not sure if removing `csc.rsp` breaks compatibility with earlier Unity/IDE versions. Can someone check? I'm assuming it was needed for something at some point? 

I still think disabling `autoReferenced` seems like a good idea, so I'll leave this pull request around for now.

**Review by JoC0de — APPROVED** [review]
I think it is even expected for editor plugins to not be auto-referenced.
The `csc.rsp` file is at least needed for the plugin to work in Unity 2018 if we increase the minimum required Unity version it could be possible that we don't need it.
